[package]
name          = "collenchyma"
description   = "fast, parallel, backend-agnostic computation on any hardware"
version       = "0.0.3"
authors       = [
"Michael Hirn <mj@autumnai.com>",
"Maximilian Goisser <max@autumnai.com"]

repository    = "https://github.com/autumnai/collenchyma"
homepage      = "https://github.com/autumnai/collenchyma"
documentation = "http://autumnai.github.io/collenchyma"
readme        = "README.md"

keywords      = ["backend", "computation", "opencl", "cuda"]
license       = "MIT"

[dependencies]
libc = "0.2"
bitflags = "0.3"
rblas = "0.0.10"
enum_primitive = "0.1.0"
byteorder = "0.4"
num = "0.1"

clippy = { version = "0.0.23", optional = true }

[features]
default = []
dev = []
lint = ["clippy"]
